name: Docker Build and Push

on:
  push:
    branches:
      - main # 或者你希望触发构建的其他分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build . -t dsmggm/jdck:latest

    - name: Push Docker image
      run: docker push dsmggm/jdck:latest
